const S = {
  root: { fontFamily: "'Noto Sans JP','Hiragino Kaku Gothic ProN',sans-serif", maxWidth: 680, margin: "0 auto", padding: "0 16px 40px", backgroundColor: "#f8fafc", minHeight: "100vh", color: "#0f172a", position: "relative" },
  loadingWrap: { display: "flex", justifyContent: "center", alignItems: "center", height: "100vh" },
  loadingText: { fontSize: 16, color: "#64748b" },
  toast: { position: "fixed", top: 16, left: "50%", transform: "translateX(-50%)", backgroundColor: "#0f172a", color: "#fff", padding: "10px 24px", borderRadius: 10, fontSize: 13, fontWeight: 600, zIndex: 9999, boxShadow: "0 4px 12px rgba(0,0,0,0.2)" },
  header: { textAlign: "center", padding: "28px 0 4px" },
  title: { fontSize: 26, fontWeight: 800, margin: 0, letterSpacing: -0.5, background: "linear-gradient(135deg,#1e3a5f,#3b82f6)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" },
  headerActions: { marginTop: 8 },
  headerBtn: { background: "none", border: "1px solid #cbd5e1", borderRadius: 8, padding: "6px 14px", fontSize: 11, color: "#64748b", cursor: "pointer", fontWeight: 600 },
  balanceCard: { background: "linear-gradient(135deg,#1e3a5f 0%,#1e40af 100%)", borderRadius: 16, padding: "24px 20px", margin: "16px 0", color: "#fff" },
  balanceLabel: { fontSize: 12, opacity: 0.8, marginBottom: 4, fontWeight: 500 },
  balanceValue: { fontSize: 30, fontWeight: 800, cursor: "pointer" },
  editHint: { fontSize: 10, opacity: 0.5, display: "block", marginTop: 2, fontWeight: 400 },
  balanceEditRow: { display: "flex", gap: 8, alignItems: "center" },
  balanceInput: { flex: 1, fontSize: 20, fontWeight: 700, padding: "8px 12px", border: "2px solid rgba(255,255,255,0.3)", borderRadius: 8, backgroundColor: "rgba(255,255,255,0.15)", color: "#fff", outline: "none" },
  btnSmall: { padding: "8px 16px", borderRadius: 8, border: "none", backgroundColor: "#fff", color: "#1e3a5f", fontWeight: 700, cursor: "pointer", fontSize: 13 },
  btnCancelSm: { backgroundColor: "rgba(255,255,255,0.2)", color: "#fff" },
  nav: { display: "flex", gap: 3, backgroundColor: "#e2e8f0", borderRadius: 12, padding: 3, marginBottom: 14 },
  navBtn: { flex: 1, padding: "9px 0", border: "none", borderRadius: 10, backgroundColor: "transparent", color: "#64748b", fontWeight: 600, fontSize: 12, cursor: "pointer", transition: "all 0.2s" },
  navBtnActive: { backgroundColor: "#fff", color: "#1e3a5f", boxShadow: "0 1px 3px rgba(0,0,0,0.1)" },
  addBtn: { width: "100%", padding: "13px", border: "2px dashed #cbd5e1", borderRadius: 12, backgroundColor: "transparent", color: "#3b82f6", fontWeight: 700, fontSize: 14, cursor: "pointer", marginBottom: 18 },
  section: { marginBottom: 24 },
  sectionTitle: { fontSize: 15, fontWeight: 700, marginBottom: 10, color: "#1e293b" },
  flexBetween: { display: "flex", justifyContent: "space-between", alignItems: "center" },
  grid3: { display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 8 },
  grid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8 },
  sumCard: { backgroundColor: "#fff", borderRadius: 12, padding: "14px 12px", textAlign: "center", boxShadow: "0 1px 3px rgba(0,0,0,0.06)" },
  sumLabel: { fontSize: 10, color: "#94a3b8", marginBottom: 2, fontWeight: 600 },
  sumValue: { fontSize: 16, fontWeight: 800 },
  miniChart: { display: "flex", gap: 6, justifyContent: "space-between", marginTop: 10 },
  miniCol: { flex: 1, display: "flex", flexDirection: "column", alignItems: "center", gap: 3, cursor: "pointer" },
  miniLabel: { fontSize: 10, color: "#94a3b8", fontWeight: 600 },
  miniBar: { width: 22, borderRadius: 4 },
  miniVal: { fontSize: 8, color: "#64748b", fontWeight: 600 },
  catBreakdown: { display: "flex", flexDirection: "column", gap: 6 },
  catRow: { display: "flex", justifyContent: "space-between", alignItems: "center", backgroundColor: "#fff", borderRadius: 8, padding: "10px 12px" },
  catLeft: { display: "flex", alignItems: "center", gap: 8, minWidth: 90 },
  catDot: { width: 8, height: 8, borderRadius: "50%", flexShrink: 0 },
  catName: { fontSize: 12, fontWeight: 600 },
  catRight: { display: "flex", alignItems: "center", gap: 8, flex: 1, justifyContent: "flex-end" },
  catBarOuter: { width: 80, height: 6, backgroundColor: "#f1f5f9", borderRadius: 3, overflow: "hidden" },
  catBarInner: { height: "100%", borderRadius: 3, transition: "width 0.3s" },
  catAmt: { fontSize: 12, fontWeight: 700, minWidth: 70, textAlign: "right" },
  catPct: { fontSize: 10, color: "#94a3b8", fontWeight: 600, minWidth: 30, textAlign: "right" },
  rankNum: { fontSize: 11, fontWeight: 700, color: "#94a3b8", minWidth: 20 },
  emptyMsg: { textAlign: "center", color: "#94a3b8", fontSize: 13, padding: "32px 16px", lineHeight: 1.7 },
  emptySmall: { color: "#94a3b8", fontSize: 13, padding: "12px 0" },
  // Items
  itemRow: { display: "flex", justifyContent: "space-between", alignItems: "center", backgroundColor: "#fff", borderRadius: 10, padding: "12px 14px", marginBottom: 6, boxShadow: "0 1px 2px rgba(0,0,0,0.04)" },
  itemLeft: { display: "flex", alignItems: "center", gap: 8, flex: 1, minWidth: 0 },
  itemDot: { width: 8, height: 8, borderRadius: "50%", flexShrink: 0 },
  itemName: { fontSize: 13, fontWeight: 700, display: "flex", alignItems: "center", gap: 6 },
  badgeOnce: { fontSize: 9, backgroundColor: "#8b5cf6", color: "#fff", padding: "1px 6px", borderRadius: 4, fontWeight: 700 },
  itemMeta: { fontSize: 10, color: "#94a3b8", marginTop: 1, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  itemRight: { textAlign: "right", flexShrink: 0 },
  itemAmt: { fontSize: 14, fontWeight: 800 },
  itemActions: { display: "flex", gap: 8, marginTop: 3, justifyContent: "flex-end" },
  actBtn: { background: "none", border: "none", fontSize: 10, color: "#3b82f6", cursor: "pointer", fontWeight: 600, padding: 0 },
  // Table
  table: { backgroundColor: "#fff", borderRadius: 12, overflow: "hidden", boxShadow: "0 1px 3px rgba(0,0,0,0.06)" },
  tHeader: { display: "flex", padding: "10px 10px", backgroundColor: "#f1f5f9", fontSize: 10, fontWeight: 700, color: "#64748b", alignItems: "center" },
  thM: { flex: 1.3 },
  thN: { flex: 1, textAlign: "right" },
  tRow: { display: "flex", padding: "10px 10px", fontSize: 12, borderTop: "1px solid #f1f5f9", alignItems: "center" },
  tdM: { flex: 1.3, fontWeight: 600 },
  tdN: { flex: 1, textAlign: "right", fontSize: 11 },
  detailBtn: { width: 28, height: 28, border: "none", backgroundColor: "#f1f5f9", borderRadius: 6, cursor: "pointer", fontSize: 10, color: "#64748b", display: "flex", alignItems: "center", justifyContent: "center" },
  // Metric
  metricCard: { backgroundColor: "#fff", borderRadius: 12, padding: "16px 14px", boxShadow: "0 1px 3px rgba(0,0,0,0.06)" },
  metricLabel: { fontSize: 10, color: "#94a3b8", fontWeight: 600 },
  metricValue: { fontSize: 20, fontWeight: 800, marginTop: 4 },
  metricSub: { fontSize: 10, color: "#94a3b8", marginTop: 2 },
  // Fixed vs Variable
  fvCard: { backgroundColor: "#fff", borderRadius: 12, padding: 16, boxShadow: "0 1px 3px rgba(0,0,0,0.06)" },
  fvRow: { display: "flex", alignItems: "center", gap: 10, marginBottom: 8 },
  fvLabel: { fontSize: 12, fontWeight: 700, minWidth: 50 },
  fvBarOuter: { flex: 1, height: 10, backgroundColor: "#f1f5f9", borderRadius: 5, overflow: "hidden" },
  fvBarInner: { height: "100%", borderRadius: 5, transition: "width 0.3s" },
  fvVal: { fontSize: 11, fontWeight: 600, minWidth: 120, textAlign: "right" },
  fvNote: { fontSize: 10, color: "#94a3b8", marginTop: 4 },
  // Trend
  trendChart: { display: "flex", gap: 4, justifyContent: "space-between", backgroundColor: "#fff", borderRadius: 12, padding: "16px 10px", boxShadow: "0 1px 3px rgba(0,0,0,0.06)" },
  trendCol: { flex: 1, display: "flex", flexDirection: "column", alignItems: "center", gap: 3 },
  trendLabel: { fontSize: 9, color: "#94a3b8", fontWeight: 600 },
  trendBar: { width: 16, borderRadius: 3 },
  trendVal: { fontSize: 7, color: "#64748b", fontWeight: 600 },
  // Report
  reportNav: { marginBottom: 12 },
  reportSelect: { padding: "8px 12px", borderRadius: 8, border: "2px solid #e2e8f0", fontSize: 14, fontWeight: 600, color: "#1e293b", backgroundColor: "#fff", cursor: "pointer", width: "100%" },
  // Modal
  overlay: { position: "fixed", inset: 0, backgroundColor: "rgba(0,0,0,0.5)", display: "flex", justifyContent: "center", alignItems: "center", zIndex: 1000, padding: 16 },
  modal: { backgroundColor: "#fff", borderRadius: 20, padding: "24px 22px", width: "100%", maxWidth: 440, maxHeight: "90vh", overflowY: "auto" },
  modalTitle: { fontSize: 18, fontWeight: 800, marginBottom: 16, textAlign: "center" },
  toggleRow: { display: "flex", gap: 8, marginBottom: 12 },
  toggleBtn: { flex: 1, padding: "10px", borderRadius: 10, border: "2px solid #e2e8f0", backgroundColor: "#fff", color: "#64748b", fontWeight: 700, fontSize: 14, cursor: "pointer" },
  toggleActive: { backgroundColor: "#22c55e", color: "#fff", borderColor: "#22c55e" },
  toggleBtnSm: { flex: 1, padding: "8px", borderRadius: 8, border: "2px solid #e2e8f0", backgroundColor: "#fff", color: "#64748b", fontWeight: 600, fontSize: 12, cursor: "pointer" },
  toggleSmActive: { backgroundColor: "#3b82f6", color: "#fff", borderColor: "#3b82f6" },
  label: { display: "block", fontSize: 11, fontWeight: 700, color: "#475569", marginBottom: 3, marginTop: 12 },
  input: { width: "100%", padding: "9px 12px", border: "2px solid #e2e8f0", borderRadius: 10, fontSize: 14, outline: "none", boxSizing: "border-box", color: "#0f172a" },
  formActions: { display: "flex", gap: 10, marginTop: 20 },
  btnPrimary: { flex: 1, padding: "12px", borderRadius: 10, border: "none", backgroundColor: "#3b82f6", color: "#fff", fontWeight: 700, fontSize: 14, cursor: "pointer" },
  btnCancel: { backgroundColor: "#e2e8f0", color: "#64748b" },
  footer: { textAlign: "center", marginTop: 28, paddingBottom: 20 },
  resetBtn: { background: "none", border: "none", color: "#94a3b8", fontSize: 12, cursor: "pointer", textDecoration: "underline" },
  // Import/Export
  ieSection: {},
  ieHead: { fontSize: 14, fontWeight: 700, marginBottom: 8, color: "#1e293b" },
  ieBtn: { padding: "10px 18px", borderRadius: 10, border: "none", backgroundColor: "#3b82f6", color: "#fff", fontWeight: 700, fontSize: 13, cursor: "pointer" },
  ieBtnSec: { backgroundColor: "#e2e8f0", color: "#475569" },
  ieNote: { fontSize: 11, color: "#94a3b8", marginTop: 8 },
  ieTextarea: { width: "100%", padding: 12, border: "2px solid #e2e8f0", borderRadius: 10, fontSize: 12, fontFamily: "monospace", resize: "vertical", boxSizing: "border-box", outline: "none" },
  ieError: { fontSize: 12, color: "#ef4444", marginTop: 4 },
};

export default S;
